###
# RankNovo configuration.
# Blank entries are interpreted as "None"
###

# Random seed to ensure reproducible results.
random_seed: 2007

# Spectrum processing options.
n_peaks: 300
min_mz: 50.5
max_mz: 4500.0
min_intensity: 0.0
remove_precursor_tol: 2.0  # Da
max_charge: 10
precursor_mass_tol: 50  # ppm
isotope_error_range: [0, 1]

# Model architecture options.
dim_model: 512
n_head: 8
dim_feedforward: 1024
n_layers: 8
dropout: 0.30
dim_intensity:
custom_encoder:
max_length: 100
residues:
  "G": 57.021464
  "A": 71.037114
  "S": 87.032028
  "P": 97.052764
  "V": 99.068414
  "T": 101.047670
  "C+57.021": 160.030649 # 103.009185 + 57.021464
  "L": 113.084064
  "I": 113.084064
  "N": 114.042927
  "D": 115.026943
  "Q": 128.058578
  "K": 128.094963
  "E": 129.042593
  "M": 131.040485
  "H": 137.058912
  "F": 147.068414
  "R": 156.101111
  "Y": 163.063329
  "W": 186.079313
  # Amino acid modifications.
  "M+15.995": 147.035400    # Met oxidation:   131.040485 + 15.994915
  "N+0.984": 115.026943     # Asn deamidation: 114.042927 +  0.984016
  "Q+0.984": 129.042594     # Gln deamidation: 128.058578 +  0.984016
  # N-terminal modifications.
  "+42.011": 42.010565      # Acetylation
  "+43.006": 43.005814      # Carbamylation
  "-17.027": -17.026549     # NH3 loss
  "+43.006-17.027": 25.980265
n_log: 1
tb_summarywriter:

# Neptune logger
enable_neptune: False
neptune_project: ""
neptune_api_token: "" 

# Use epochs instead of iters
warmup_iters: 
max_iters: 

max_epochs: 5
warm_up_epochs: 1
learning_rate: 1e-4
weight_decay: 8e-5
gradient_clip_val: 1.5
gradient_clip_algorithm: "norm"
accumulate_grad_batches: 1
sync_batchnorm: False
SWA: False #  
# Amount of label smoothing when computing the training loss
train_label_smoothing: 0.0

# Training/inference options.
train_batch_size: 256
predict_batch_size: 256
n_beams: 0
val_check_interval: 0.125

logger:

num_sanity_val_steps: 0

train_from_scratch: True
load_file_name:

save_model: True
model_save_folder_path: ""
save_weights_only: True
every_n_train_steps: 2500

# Disable usage of a GPU (including Apple MPS):
no_gpu: False
n_gpus: 
n_nodes: 1

species:


model_id: "model_6"

use_col: True
save: False
